name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1


      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          connect_timeout: 10s
          script: |
            echo "Kill all processes"
            killall -9 python3
            killall -9 node
            cd scientific-purpose-harvester
            echo "Git pull"
            git pull
            cd harvester
            echo "start python"
            python3 api.py & disown
            cd ../svelete_harvester/
            rm -r node_modules/
            echo "npm instal"
            npm install
            echo "npm run dev"
            HOST=85.214.28.167 npm run dev & disown
            echo finished
